/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.service.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.sql.Time;
import java.util.*;
public class App {


    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner=new Scanner(System.in);
        int option =0;
        UserBookingService userBookingService;
        try{
            userBookingService=new UserBookingService();
        }catch(IOException ex){
            System.out.println("There is something wrong");
            return;

        }
       while(option!=7){
           System.out.println("Choose an Option");
           System.out.println("1. Sign Up");
           System.out.println("2. Login");
           System.out.println("3. Fetch Bookings");
           System.out.println("4. Search Trains");
           System.out.println("5. Book a Seat");
           System.out.println("6. Cancel My Booking");
           System.out.println("7. Exit the App");
           option =scanner.nextInt();
           Train trainSelectedForBooking = new Train();
           switch(option){
               case 1:
                   System.out.println("Enter the username to signup");
                   String nameToSignUp=scanner.next();
                   System.out.println("Enter the Password to signup");
                   String passwordToSignUp=scanner.next();
                   User userToSignUp= new User(nameToSignUp,passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp
                   ), new ArrayList<>(), UUID.randomUUID().toString());
                   userBookingService.signUp(userToSignUp);
                   break;
               case 2:
                   System.out.println("Enter the username to signup");
                   String nameToLogin=scanner.next();
                   System.out.println("Enter the Password to signup");
                   String passwordToLogin=scanner.next();
                   User userToLogin= new User(nameToLogin,passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin
                   ), new ArrayList<>(), UUID.randomUUID().toString());
                   try{
                      userBookingService=new UserBookingService(userToLogin);
                   }catch(IOException ex){
                       return;
                   }
                   break;
               case 3:
                   System.out.println("Fetching your Bookings ");
                   userBookingService.fetchBooking();
                   break;
               case 4:
                   System.out.println("Type Your Source station :");
                   String source=scanner.next();
                   System.out.println("Type your destination station:");
                   String destination=scanner.next();
                   List<Train> trains=userBookingService.getTrains(source,destination);
                   int index=1;
                   for (Train t: trains){
                       System.out.println(index+" Train id : "+t.getTrainId());
                       index++;
                       for (Map.Entry<String, String> entry: t.getStationTimes().entrySet()){
                           System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                       }
                   }
                   System.out.println("Select a train by typing 1,2,3...");
                   trainSelectedForBooking = trains.get(scanner.nextInt());
                   break;
//               case 5:
//                   System.out.println("Select a seat out of these seats");
//
//                   List<List<Integer>> seats=userBookingService.fetchSeats(trainSelectedForBooking);
//                   List<List<Integer>> seatsSelected=


           }

       }
    }

}
